name: GH actions triggering on while creating an issues in the repository
on: issues
jobs:
  information:
    runs-on: ubuntu-latest
    steps:
      - name: Output event details on the console
        run: "${{ toJson(github.event) }}"
