name: Lint, Test and Deploy on Push

on:
  push:
    branches:
      - master

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code from the repository
        uses: actions/checkout@v4
      - name: Installing the latest Node.js
        uses: actions/setup-node@v4
      - name: Installing the dependencies
        run: npm install
      # - name: Building the project
      #   run: npm run build
      - name: Linting the script
        run: npm run lint
      - name: Testing the script
        run: npm run test
      - name: Building the project
        run: npm run build
      - name: Deploying the script
        run: echo "Projects are getting deployed...."
