name: Lint, Test and Deploy on Push
on:
  push:
    branches:
      - master
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code from the repos
        uses: actions/checkout@v4
      - name: installing the lastest node
        uses: actions/setup-node@v4
      - name: Installing the dependencies
        run: npm install
      #- name: Building the project
      # run: npm run build
      - name: Linting the script
        run: npm run lint
      - name: Testing the script
        run: npm run test
      - name: Building the project
        run: npm run build
      - name: Deploying the script
        #run: npm run dev
        run: echo "Projects are getting deployed...."
      #- name: Updating the package list
      #run: apt-get update -y
  #second-job:
  # needs: first-job
  #runs-on: ubuntu-latest
  #steps:
  # - name: Building the project
  #  run: npm run build
  #- name: Linting the script
  # run: npm run lint
  #- name: Testing the script
  # run: npm run test
  #- name: Deploying the script
  # run: npm run dev
